server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://tututeam.top:3306/industry?serverTimezone=Asia/Shanghai
#    username: root
    username: fxc
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false